use std::collections::HashSet;
use std::fmt::Write as FmtWrite;

use crate::model::{ServiceModel, Shape};
use crate::resolve::ReachableShapes;

// ─────────────────────────────────────────────────────────────────────────────
// Protocol helpers
// ─────────────────────────────────────────────────────────────────────────────

/// EC2 uses protocol "ec2" in the spec, but it's wire-compatible with "query".
fn is_query_protocol(proto: &str) -> bool {
    matches!(proto, "query" | "ec2")
}

// ─────────────────────────────────────────────────────────────────────────────
// Public entry point
// ─────────────────────────────────────────────────────────────────────────────

pub struct EmitCtx<'a> {
    pub model:           &'a ServiceModel,
    pub reachable:       &'a ReachableShapes,
    pub topo_order:      &'a [String],
    pub operations:      &'a [&'a str],
    pub service_name:    &'a str,
    /// Crate path for the aws-api runtime. Defaults to `"aws_api"`.
    /// Set to `"crate"` if the generated code lives inside the aws-api crate itself.
    pub runtime_crate:   &'a str,
    pub sync:            bool,
}

pub fn emit(ctx: &EmitCtx<'_>) -> String {
    let mut out = String::with_capacity(64 * 1024);
    let proto = ctx.model.metadata.protocol.as_str();

    writeln!(out, "// Auto-generated by aws-codegen — DO NOT EDIT").unwrap();
    writeln!(out, "// service={} protocol={} version={}",
        ctx.service_name,
        proto,
        ctx.model.metadata.api_version,
    ).unwrap();
    // NOTE: the including module should add #[allow(dead_code, non_snake_case, ...)]
    writeln!(out).unwrap();
    let rt = ctx.runtime_crate;
    writeln!(out, "use {rt}::aws::{{Client, AwsError}};").unwrap();
    writeln!(out).unwrap();

    // Emit all shape types in dependency order
    for shape_name in ctx.topo_order {
        let Some(shape) = ctx.model.shapes.get(shape_name.as_str()) else { continue };

        // Skip primitives (string/integer/etc with no enum values) — they inline
        if shape.is_primitive() { continue; }

        let in_input  = ctx.reachable.input.contains(shape_name);
        let in_output = ctx.reachable.output.contains(shape_name);

        match shape.shape_type.as_str() {
            "structure" => emit_structure(&mut out, ctx, shape_name, shape, in_input, in_output),
            "list"      => emit_list_wrapper(&mut out, ctx, shape_name, shape, in_input, in_output),
            "map"       => emit_map_type(&mut out, ctx, shape_name, shape, in_input, in_output),
            "string" if shape.enum_values.is_some() => emit_string_enum(&mut out, ctx, shape_name, shape),
            _ => {}
        }
    }

    // Emit operation async functions
    for &op_name in ctx.operations {
        let Some(op) = ctx.model.operations.get(op_name) else { continue };
        match proto {
            "query"     => emit_query_op(&mut out, ctx, op_name, op),
            "json"      => emit_json_op(&mut out, ctx, op_name, op),
            "rest-json" => emit_rest_json_op(&mut out, ctx, op_name, op),
            "rest-xml"  => emit_rest_xml_op(&mut out, ctx, op_name, op),
            _           => emit_query_op(&mut out, ctx, op_name, op), // fallback
        }
    }

    // Strip async/await for sync mode
    if ctx.sync {
        out = out.replace("pub async fn ", "pub fn ");
        out = out.replace(".await?", "?");
        out = out.replace(".await", "");
    }

    out
}

// ─────────────────────────────────────────────────────────────────────────────
// Shape emitters
// ─────────────────────────────────────────────────────────────────────────────

fn emit_structure(
    out:       &mut String,
    ctx:       &EmitCtx<'_>,
    name:      &str,
    shape:     &Shape,
    in_input:  bool,
    in_output: bool,
) {
    let rt = ctx.runtime_crate;
    let rust_name = to_pascal(name);
    let req_set: HashSet<&str> = shape.required.iter().map(String::as_str).collect();
    let proto = ctx.model.metadata.protocol.as_str();
    let is_json = matches!(proto, "json" | "rest-json");
    let is_xml  = is_query_protocol(proto) || proto == "rest-xml";

    // Doc comment
    if let Some(doc) = &shape.documentation {
        let first_line = doc.lines().next().unwrap_or("").trim();
        if !first_line.is_empty() {
            writeln!(out, "/// {}", strip_html(first_line)).unwrap();
        }
    }

    // Struct definition — no serde derives
    writeln!(out, "#[derive(Debug, Clone, Default)]").unwrap();
    writeln!(out, "pub struct {} {{", rust_name).unwrap();

    for (member_name, member_ref) in &shape.members {
        let rust_field = to_snake(member_name);
        let rust_type  = rust_field_type(ctx, member_ref, in_output);
        let required   = req_set.contains(member_name.as_str());

        if required {
            writeln!(out, "    pub {rust_field}: {rust_type},").unwrap();
        } else {
            writeln!(out, "    pub {rust_field}: Option<{rust_type}>,").unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // ── Builder methods for input structs ───────────────────────────────
    if in_input {
        writeln!(out, "impl {rust_name} {{").unwrap();
        for (member_name, member_ref) in &shape.members {
            let rust_field = to_snake(member_name);
            let rust_type  = rust_field_type(ctx, member_ref, false);
            let required   = req_set.contains(member_name.as_str());
            let member_shape = ctx.model.shapes.get(&member_ref.shape);
            let is_list = member_shape.map(|s| s.shape_type == "list").unwrap_or(false);

            if is_list && !required {
                // List field: push a single item into the list
                let item_type = member_shape
                    .and_then(|s| s.member.as_ref())
                    .map(|m| rust_type_by_name(&m.shape, ctx.model, false))
                    .unwrap_or_else(|| "String".to_string());
                if item_type == "String" {
                    writeln!(out, "    pub fn {rust_field}(mut self, v: impl Into<String>) -> Self {{").unwrap();
                    writeln!(out, "        self.{rust_field}.get_or_insert_with(Default::default).item.push(v.into());").unwrap();
                } else {
                    writeln!(out, "    pub fn {rust_field}(mut self, v: {item_type}) -> Self {{").unwrap();
                    writeln!(out, "        self.{rust_field}.get_or_insert_with(Default::default).item.push(v);").unwrap();
                }
                writeln!(out, "        self").unwrap();
                writeln!(out, "    }}").unwrap();
            } else if required {
                // Required field: set directly
                if rust_type == "String" {
                    writeln!(out, "    pub fn {rust_field}(mut self, v: impl Into<String>) -> Self {{").unwrap();
                    writeln!(out, "        self.{rust_field} = v.into();").unwrap();
                } else {
                    writeln!(out, "    pub fn {rust_field}(mut self, v: {rust_type}) -> Self {{").unwrap();
                    writeln!(out, "        self.{rust_field} = v;").unwrap();
                }
                writeln!(out, "        self").unwrap();
                writeln!(out, "    }}").unwrap();
            } else {
                // Optional field: wrap in Some
                if rust_type == "String" {
                    writeln!(out, "    pub fn {rust_field}(mut self, v: impl Into<String>) -> Self {{").unwrap();
                    writeln!(out, "        self.{rust_field} = Some(v.into());").unwrap();
                } else {
                    writeln!(out, "    pub fn {rust_field}(mut self, v: {rust_type}) -> Self {{").unwrap();
                    writeln!(out, "        self.{rust_field} = Some(v);").unwrap();
                }
                writeln!(out, "        self").unwrap();
                writeln!(out, "    }}").unwrap();
            }
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // ── FromXml impl for XML output (query/ec2, rest-xml) ──────────────
    if in_output && is_xml {
        writeln!(out, "impl {rt}::aws::xml::FromXml for {rust_name} {{").unwrap();
        writeln!(out, "    fn from_xml(node: &{rt}::aws::xml::XmlNode) -> Result<Self, String> {{").unwrap();
        writeln!(out, "        Ok(Self {{").unwrap();

        for (member_name, member_ref) in &shape.members {
            let rust_field = to_snake(member_name);
            let required   = req_set.contains(member_name.as_str());
            let member_shape = ctx.model.shapes.get(&member_ref.shape);
            let is_primitive = member_shape.map(|s| s.is_primitive()).unwrap_or(true);
            let is_list = member_shape.map(|s| s.shape_type == "list").unwrap_or(false);

            // Compute XML element name
            let wire = member_ref.wire_name(member_name);
            let xml_name = if proto == "rest-xml" {
                // rest-xml: use locationName or PascalCase member name
                wire.to_string()
            } else {
                // query/ec2: use locationName or camelCase
                if wire != member_name { wire.to_string() } else { to_camel(member_name) }
            };

            if is_list {
                // Lists: the list wrapper's FromXml handles child elements
                if required {
                    writeln!(out, "            {rust_field}: {t}::from_xml(node.child(\"{xml_name}\").unwrap_or(node))?,",
                        t = rust_field_type(ctx, member_ref, true)).unwrap();
                } else {
                    writeln!(out, "            {rust_field}: node.child(\"{xml_name}\").map(|n| {t}::from_xml(n)).transpose()?,",
                        t = rust_field_type(ctx, member_ref, true)).unwrap();
                }
            } else if is_primitive {
                // Primitives: get text from child element
                if required {
                    writeln!(out, "            {rust_field}: node.child(\"{xml_name}\").map(|n| {rt}::aws::xml::FromXml::from_xml(n)).transpose()?.unwrap_or_default(),").unwrap();
                } else {
                    writeln!(out, "            {rust_field}: node.child(\"{xml_name}\").map(|n| {rt}::aws::xml::FromXml::from_xml(n)).transpose()?,").unwrap();
                }
            } else {
                // Nested struct
                if required {
                    writeln!(out, "            {rust_field}: node.child(\"{xml_name}\").map(|n| {rt}::aws::xml::FromXml::from_xml(n)).transpose()?.unwrap_or_default(),").unwrap();
                } else {
                    writeln!(out, "            {rust_field}: node.child(\"{xml_name}\").map(|n| {rt}::aws::xml::FromXml::from_xml(n)).transpose()?,").unwrap();
                }
            }
        }

        writeln!(out, "        }})").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // ── FromJsonValue impl for JSON output (json, rest-json) ───────────
    if in_output && is_json {
        writeln!(out, "impl {rt}::aws::json::FromJsonValue for {rust_name} {{").unwrap();
        writeln!(out, "    fn from_json(v: &{rt}::serde_json::Value) -> Self {{").unwrap();
        writeln!(out, "        Self {{").unwrap();

        for (member_name, member_ref) in &shape.members {
            let rust_field = to_snake(member_name);
            let required   = req_set.contains(member_name.as_str());
            let member_shape = ctx.model.shapes.get(&member_ref.shape);
            let is_primitive_str = member_shape.map(|s| s.shape_type == "string" && s.enum_values.is_none()).unwrap_or(false);
            let is_bool = member_shape.map(|s| s.shape_type == "boolean").unwrap_or(false);
            // JSON key is PascalCase member name
            if required {
                if is_primitive_str {
                    writeln!(out, "            {rust_field}: v.get(\"{member_name}\").and_then(|v| v.as_str()).unwrap_or(\"\").to_string(),").unwrap();
                } else if is_bool {
                    writeln!(out, "            {rust_field}: v.get(\"{member_name}\").and_then(|v| v.as_bool()).unwrap_or(false),").unwrap();
                } else {
                    writeln!(out, "            {rust_field}: v.get(\"{member_name}\").map(|v| {rt}::aws::json::FromJsonValue::from_json(v)).unwrap_or_default(),").unwrap();
                }
            } else if is_primitive_str {
                writeln!(out, "            {rust_field}: v.get(\"{member_name}\").and_then(|v| v.as_str()).map(String::from),").unwrap();
            } else if is_bool {
                writeln!(out, "            {rust_field}: v.get(\"{member_name}\").and_then(|v| v.as_bool()),").unwrap();
            } else {
                writeln!(out, "            {rust_field}: v.get(\"{member_name}\").filter(|v| !v.is_null()).map(|v| {rt}::aws::json::FromJsonValue::from_json(v)),").unwrap();
            }
        }

        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // ── ToJsonValue impl for JSON input (json, rest-json) ──────────────
    if in_input && is_json {
        writeln!(out, "impl {rt}::aws::json::ToJsonValue for {rust_name} {{").unwrap();
        writeln!(out, "    fn to_json(&self) -> {rt}::serde_json::Value {{").unwrap();
        writeln!(out, "        let mut m = {rt}::serde_json::Map::new();").unwrap();

        for (member_name, member_ref) in &shape.members {
            let rust_field = to_snake(member_name);
            let required   = req_set.contains(member_name.as_str());

            // Skip location-annotated members (they go in URI/query/headers, not body)
            let has_location = member_ref.location.as_deref()
                .map(|loc| matches!(loc, "uri" | "querystring" | "header" | "headers"))
                .unwrap_or(false);
            if has_location { continue; }

            if required {
                writeln!(out, "        m.insert(\"{member_name}\".into(), {rt}::aws::json::ToJsonValue::to_json(&self.{rust_field}));").unwrap();
            } else {
                writeln!(out, "        if let Some(ref v) = self.{rust_field} {{ m.insert(\"{member_name}\".into(), {rt}::aws::json::ToJsonValue::to_json(v)); }}").unwrap();
            }
        }

        writeln!(out, "        {rt}::serde_json::Value::Object(m)").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // QueryEncode impl for input structs in query-protocol services
    if in_input && is_query_protocol(&ctx.model.metadata.protocol) {
        emit_query_encode_impl(out, ctx, name, shape, &req_set);
    }
}

fn emit_query_encode_impl(
    out:     &mut String,
    ctx:     &EmitCtx<'_>,
    name:    &str,
    shape:   &Shape,
    req_set: &HashSet<&str>,
) {
    let rt = ctx.runtime_crate;
    let rust_name = to_pascal(name);
    writeln!(out, "impl {rt}::aws::query_proto::QueryEncode for {} {{", rust_name).unwrap();
    writeln!(out, "    fn encode(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
    writeln!(out, "        #[allow(unused_imports)]").unwrap();
    writeln!(out, "        use {rt}::aws::query_proto::{{QueryEncode as _, ToAwsStr as _}};").unwrap();
    writeln!(out, "        let p: String = if prefix.is_empty() {{ String::new() }} else {{ format!(\"{{}}.\", prefix) }};").unwrap();

    for (member_name, member_ref) in &shape.members {
        let rust_field = to_snake(member_name);
        // For query protocol encoding, use the PascalCase member name from the
        // botocore spec, not the camelCase locationName (which is for XML parsing).
        let wire_name  = member_name.as_str();
        let required   = req_set.contains(member_name.as_str());
        let member_shape = ctx.model.shapes.get(&member_ref.shape);

        let is_list = member_shape.map(|s| s.shape_type == "list").unwrap_or(false);
        let is_struct = member_shape.map(|s| s.shape_type == "structure").unwrap_or(false);
        let is_map = member_shape.map(|s| s.shape_type == "map").unwrap_or(false);

        if required {
            write!(out, "        ").unwrap();
        } else {
            writeln!(out, "        if let Some(val) = &self.{rust_field} {{").unwrap();
            write!(out, "            ").unwrap();
        }

        if is_list {
            // For query encoding, use the member's locationName if present
            // (e.g., Values -> "Value"), otherwise fall back to the member name.
            let list_wire = member_ref.location_name.as_deref().unwrap_or(wire_name);
            if required {
                writeln!(out,
                    "self.{rust_field}.encode(&format!(\"{{p}}{list_wire}\"), out);",
                ).unwrap();
            } else {
                writeln!(out,
                    "val.encode_items(&format!(\"{{p}}{list_wire}\"), out);",
                ).unwrap();
            }
        } else if is_struct || is_map {
            if required {
                writeln!(out,
                    "self.{rust_field}.encode(&format!(\"{{p}}{wire_name}\"), out);",
                ).unwrap();
            } else {
                writeln!(out,
                    "val.encode(&format!(\"{{p}}{wire_name}\"), out);",
                ).unwrap();
            }
        } else {
            // Primitive: push directly
            if required {
                writeln!(out,
                    "out.push((format!(\"{{p}}{wire_name}\"), self.{rust_field}.to_aws_str()));",
                ).unwrap();
            } else {
                writeln!(out,
                    "out.push((format!(\"{{p}}{wire_name}\"), val.to_aws_str()));",
                ).unwrap();
            }
        }

        if !required {
            writeln!(out, "        }}").unwrap();
        }
    }

    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_list_wrapper(
    out:       &mut String,
    ctx:       &EmitCtx<'_>,
    name:      &str,
    shape:     &Shape,
    in_input:  bool,
    in_output: bool,
) {
    let rt = ctx.runtime_crate;
    let proto = ctx.model.metadata.protocol.as_str();
    let is_json = matches!(proto, "json" | "rest-json");
    let is_xml  = is_query_protocol(proto) || proto == "rest-xml";
    let rust_name = to_pascal(name);
    let item_ref  = match &shape.member {
        Some(m) => m,
        None    => return,
    };
    let item_rust = rust_type_by_name(&item_ref.shape, ctx.model, in_output);
    // The XML element name for list items (from member.locationName, defaulting to "member")
    let item_xml  = item_ref.location_name.as_deref().unwrap_or("member");

    // Struct definition — no serde
    writeln!(out, "#[derive(Debug, Clone, Default)]").unwrap();
    writeln!(out, "pub struct {rust_name} {{").unwrap();
    writeln!(out, "    pub item: Vec<{item_rust}>,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Convenience: From<Vec<T>>
    writeln!(out, "impl From<Vec<{item_rust}>> for {rust_name} {{").unwrap();
    writeln!(out, "    fn from(v: Vec<{item_rust}>) -> Self {{ Self {{ item: v }} }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // FromXml for XML output
    if in_output && is_xml {
        writeln!(out, "impl {rt}::aws::xml::FromXml for {rust_name} {{").unwrap();
        writeln!(out, "    fn from_xml(node: &{rt}::aws::xml::XmlNode) -> Result<Self, String> {{").unwrap();
        writeln!(out, "        let items = node.children(\"{item_xml}\")").unwrap();
        writeln!(out, "            .into_iter()").unwrap();
        writeln!(out, "            .map(|n| {rt}::aws::xml::FromXml::from_xml(n))").unwrap();
        writeln!(out, "            .collect::<Result<Vec<_>, _>>()?;").unwrap();
        writeln!(out, "        Ok(Self {{ item: items }})").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // FromJsonValue for JSON output
    if in_output && is_json {
        writeln!(out, "impl {rt}::aws::json::FromJsonValue for {rust_name} {{").unwrap();
        writeln!(out, "    fn from_json(v: &{rt}::serde_json::Value) -> Self {{").unwrap();
        writeln!(out, "        let items = v.as_array()").unwrap();
        writeln!(out, "            .map(|arr| arr.iter().map(|e| {rt}::aws::json::FromJsonValue::from_json(e)).collect())").unwrap();
        writeln!(out, "            .unwrap_or_default();").unwrap();
        writeln!(out, "        Self {{ item: items }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // ToJsonValue for JSON input
    if in_input && is_json {
        writeln!(out, "impl {rt}::aws::json::ToJsonValue for {rust_name} {{").unwrap();
        writeln!(out, "    fn to_json(&self) -> {rt}::serde_json::Value {{").unwrap();
        writeln!(out, "        {rt}::serde_json::Value::Array(self.item.iter().map(|v| {rt}::aws::json::ToJsonValue::to_json(v)).collect())").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // QueryEncode for lists used in query-protocol inputs
    if in_input && is_query_protocol(proto) {
        writeln!(out, "impl {rt}::aws::query_proto::QueryEncode for {rust_name} {{").unwrap();
        writeln!(out, "    fn encode(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
        writeln!(out, "        self.encode_items(prefix, out);").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out, "impl {rust_name} {{").unwrap();
        writeln!(out, "    pub fn encode_items(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
        writeln!(out, "        use {rt}::aws::query_proto::QueryEncode as _;").unwrap();
        writeln!(out, "        for (i, item) in self.item.iter().enumerate() {{").unwrap();
        writeln!(out, "            item.encode(&format!(\"{{}}.{{}}\", prefix, i + 1), out);").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}

fn emit_string_enum(out: &mut String, ctx: &EmitCtx<'_>, name: &str, shape: &Shape) {
    let rt = ctx.runtime_crate;
    let proto = ctx.model.metadata.protocol.as_str();
    let is_json = matches!(proto, "json" | "rest-json");
    let is_xml  = is_query_protocol(proto) || proto == "rest-xml";
    let rust_name  = to_pascal(name);
    let enum_vals  = shape.enum_values.as_ref().unwrap();

    // Enum definition — no serde
    writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub enum {rust_name} {{").unwrap();
    for v in enum_vals {
        let variant = sanitize_enum_variant(v);
        writeln!(out, "    {variant},").unwrap();
    }
    writeln!(out, "    Unknown,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // from_str helper (shared by FromXml and FromJsonValue)
    writeln!(out, "impl {rust_name} {{").unwrap();
    writeln!(out, "    fn from_str(s: &str) -> Self {{").unwrap();
    writeln!(out, "        match s {{").unwrap();
    for v in enum_vals {
        let variant = sanitize_enum_variant(v);
        writeln!(out, "            \"{v}\" => Self::{variant},").unwrap();
    }
    writeln!(out, "            _ => Self::Unknown,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // ToAwsStr (used by QueryEncode and Display)
    writeln!(out, "impl {rt}::aws::query_proto::ToAwsStr for {rust_name} {{").unwrap();
    writeln!(out, "    fn to_aws_str(&self) -> String {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for v in enum_vals {
        let variant = sanitize_enum_variant(v);
        writeln!(out, "            Self::{variant} => \"{v}\".to_string(),").unwrap();
    }
    writeln!(out, "            Self::Unknown => \"unknown\".to_string(),").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Display
    writeln!(out, "impl std::fmt::Display for {rust_name} {{").unwrap();
    writeln!(out, "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{").unwrap();
    writeln!(out, "        use {rt}::aws::query_proto::ToAwsStr as _;").unwrap();
    writeln!(out, "        f.write_str(&self.to_aws_str())").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Default
    writeln!(out, "impl Default for {rust_name} {{").unwrap();
    writeln!(out, "    fn default() -> Self {{ Self::Unknown }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // FromXml
    if is_xml {
        writeln!(out, "impl {rt}::aws::xml::FromXml for {rust_name} {{").unwrap();
        writeln!(out, "    fn from_xml(node: &{rt}::aws::xml::XmlNode) -> Result<Self, String> {{").unwrap();
        writeln!(out, "        Ok(Self::from_str(&node.text().unwrap_or_default()))").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // FromJsonValue
    if is_json {
        writeln!(out, "impl {rt}::aws::json::FromJsonValue for {rust_name} {{").unwrap();
        writeln!(out, "    fn from_json(v: &{rt}::serde_json::Value) -> Self {{").unwrap();
        writeln!(out, "        Self::from_str(v.as_str().unwrap_or(\"\"))").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // ToJsonValue
    if is_json {
        writeln!(out, "impl {rt}::aws::json::ToJsonValue for {rust_name} {{").unwrap();
        writeln!(out, "    fn to_json(&self) -> {rt}::serde_json::Value {{").unwrap();
        writeln!(out, "        use {rt}::aws::query_proto::ToAwsStr as _;").unwrap();
        writeln!(out, "        {rt}::serde_json::Value::String(self.to_aws_str())").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // QueryEncode
    writeln!(out, "impl {rt}::aws::query_proto::QueryEncode for {rust_name} {{").unwrap();
    writeln!(out, "    fn encode(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
    writeln!(out, "        use {rt}::aws::query_proto::ToAwsStr as _;").unwrap();
    writeln!(out, "        out.push((prefix.to_string(), self.to_aws_str()));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

// ─────────────────────────────────────────────────────────────────────────────
// Operation emitters
// ─────────────────────────────────────────────────────────────────────────────

fn emit_query_op(
    out:    &mut String,
    ctx:    &EmitCtx<'_>,
    name:   &str,
    op:     &crate::model::Operation,
) {
    let rt = ctx.runtime_crate;
    let fn_name    = to_snake(name);
    let endpoint   = &ctx.model.metadata.endpoint_prefix;
    let version    = &ctx.model.metadata.api_version;

    let input_type  = op.input.as_ref().map(|r| to_pascal(&r.shape));
    let output_type = op.output.as_ref()
        .map(|r| to_pascal(&r.shape))
        .unwrap_or_else(|| "()".to_string());

    // Determine if we need to unwrap a resultWrapper intermediate element.
    //
    // EC2  → resultWrapper = "DescribeInstancesResponse" (ends with "Response")
    //        quick-xml reads root element as the struct directly → no envelope needed.
    // IAM  → resultWrapper = "GetUserResult" (ends with "Result")
    //        Response body has an extra <GetUserResult> child wrapping the output.
    let wrapper_element: Option<&str> = op.result_wrapper.as_deref().and_then(|rw| {
        if output_type != "()" && !rw.ends_with("Response") {
            Some(rw)
        } else {
            None
        }
    });

    // For result-wrapper unwrapping, emit a FromXml wrapper that extracts the child element.
    if let Some(wrapper) = wrapper_element {
        let env_name = format!("{name}Envelope__");
        writeln!(out, "struct {env_name};").unwrap();
        writeln!(out, "impl {env_name} {{").unwrap();
        writeln!(out, "    fn unwrap(node: &{rt}::aws::xml::XmlNode) -> Result<{output_type}, String> {{").unwrap();
        writeln!(out, "        let child = node.child(\"{wrapper}\")").unwrap();
        writeln!(out, "            .ok_or_else(|| \"missing {wrapper} element\".to_string())?;").unwrap();
        writeln!(out, "        {rt}::aws::xml::FromXml::from_xml(child)").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    let input_param = input_type.as_ref()
        .map(|t| format!(", input: {t}"))
        .unwrap_or_default();

    writeln!(out, "pub async fn {fn_name}(").unwrap();
    writeln!(out, "    client: &Client{input_param},").unwrap();
    writeln!(out, ") -> Result<{output_type}, AwsError> {{").unwrap();

    if input_type.is_some() {
        writeln!(out, "    use {rt}::aws::query_proto::QueryEncode as _;").unwrap();
        writeln!(out, "    let mut params: Vec<(String, String)> = vec![];").unwrap();
        writeln!(out, "    input.encode(\"\", &mut params);").unwrap();
    } else {
        writeln!(out, "    let params: Vec<(String, String)> = vec![];").unwrap();
    }

    if output_type == "()" {
        writeln!(out, "    client.query_request_void(\"{endpoint}\", \"{version}\", \"{name}\", params).await").unwrap();
    } else if wrapper_element.is_some() {
        let env_name = format!("{name}Envelope__");
        // query_request returns the XML root; we need to unwrap the wrapper child
        writeln!(out, "    let root: {rt}::aws::xml::XmlNode = {{").unwrap();
        writeln!(out, "        use {rt}::aws::query_proto::QueryEncode as _;").unwrap();
        writeln!(out, "        // Build and send the request, get raw XML back").unwrap();
        writeln!(out, "        client.query_request_raw(\"{endpoint}\", \"{version}\", \"{name}\", params).await?").unwrap();
        writeln!(out, "    }};").unwrap();
        writeln!(out, "    {env_name}::unwrap(&root).map_err(|e| {rt}::aws::AwsError::XmlParse(e))").unwrap();
    } else {
        writeln!(out, "    client.query_request(\"{endpoint}\", \"{version}\", \"{name}\", params).await").unwrap();
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_json_op(
    out:    &mut String,
    ctx:    &EmitCtx<'_>,
    name:   &str,
    op:     &crate::model::Operation,
) {
    let fn_name      = to_snake(name);
    let endpoint     = &ctx.model.metadata.endpoint_prefix;
    let target_pfx   = ctx.model.metadata.target_prefix.as_deref().unwrap_or("");
    let target       = format!("{target_pfx}.{name}");

    let input_type  = op.input.as_ref().map(|r| to_pascal(&r.shape));
    let output_type = op.output.as_ref()
        .map(|r| to_pascal(&r.shape))
        .unwrap_or_else(|| "()".to_string());

    let input_param = input_type.as_ref()
        .map(|t| format!(", input: {t}"))
        .unwrap_or_default();

    writeln!(out, "pub async fn {fn_name}(").unwrap();
    writeln!(out, "    client: &Client{input_param},").unwrap();
    writeln!(out, ") -> Result<{output_type}, AwsError> {{").unwrap();

    if input_type.is_some() {
        writeln!(out, "    client.json_request(\"{endpoint}\", \"{target}\", &input).await").unwrap();
    } else {
        writeln!(out, "    client.json_request(\"{endpoint}\", \"{target}\", &()).await").unwrap();
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_rest_json_op(
    out:    &mut String,
    ctx:    &EmitCtx<'_>,
    name:   &str,
    op:     &crate::model::Operation,
) {
    use crate::model::ShapeRef;

    let rt           = ctx.runtime_crate;
    let fn_name      = to_snake(name);
    let endpoint     = &ctx.model.metadata.endpoint_prefix;

    let http         = op.http.as_ref();
    let method       = http.map(|h| h.method.as_str()).unwrap_or("POST");
    let uri_template = http.map(|h| h.request_uri.as_str()).unwrap_or("/");

    let input_type  = op.input.as_ref().map(|r| to_pascal(&r.shape));
    let output_type = op.output.as_ref()
        .map(|r| to_pascal(&r.shape))
        .unwrap_or_else(|| "()".to_string());

    let input_param = input_type.as_ref()
        .map(|t| format!(", input: {t}"))
        .unwrap_or_default();

    writeln!(out, "pub async fn {fn_name}(").unwrap();
    writeln!(out, "    client: &Client{input_param},").unwrap();
    writeln!(out, ") -> Result<{output_type}, AwsError> {{").unwrap();

    if input_type.is_some() {
        // Collect members by location from the input shape
        let input_shape_name = op.input.as_ref().map(|r| r.shape.as_str()).unwrap_or("");
        let members: Vec<(String, ShapeRef)> = ctx.model.shapes
            .get(input_shape_name)
            .map(|s| s.members.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
            .unwrap_or_default();

        // Build URI: replace {TemplateName} segments
        // Template segments use PascalCase in the spec (e.g., {FunctionName})
        // URI template → collect uri-location members
        // URI template → collect uri-location members
        let uri_members: Vec<_> = members.iter()
            .filter(|(_, r)| r.location.as_deref() == Some("uri"))
            .collect();

        // Rewrite the template format! — replace {X} with {x} for Rust format! compat
        let mut fmt_str = uri_template.to_string();
        let mut fmt_args = String::new();
        for (mname, _mref) in &uri_members {
            let placeholder = format!("{{{mname}}}");
            let snake = to_snake(mname);
            if fmt_str.contains(&placeholder) {
                fmt_str = fmt_str.replace(&placeholder, "{}");
                fmt_args.push_str(&format!(
                    "    &{rt}::aws::client::percent_encode(&input.{snake}),\n",
                ));
            }
        }

        if uri_members.is_empty() {
            writeln!(out, "    let uri = \"{uri_template}\";").unwrap();
        } else {
            writeln!(out, "    let uri = format!(\"{fmt_str}\",").unwrap();
            writeln!(out, "{fmt_args}    );").unwrap();
        }

        // Collect querystring members
        let qs_members: Vec<_> = members.iter()
            .filter(|(_, r)| r.location.as_deref() == Some("querystring"))
            .collect();

        writeln!(out, "    let mut _query: Vec<(String, String)> = vec![];").unwrap();
        for (mname, _mref) in &qs_members {
            let snake = to_snake(mname);
            let wire  = _mref.wire_name(mname);
            writeln!(out,
                "    if let Some(ref v) = input.{snake} {{ _query.push((\"{wire}\".into(), v.to_string())); }}",
            ).unwrap();
        }

        // Collect header members
        let hdr_members: Vec<_> = members.iter()
            .filter(|(_, r)| matches!(r.location.as_deref(), Some("header") | Some("headers")))
            .collect();

        writeln!(out, "    let mut _headers: Vec<(String, String)> = vec![];").unwrap();
        for (mname, mref) in &hdr_members {
            let snake = to_snake(mname);
            let hdr_name = mref.location_name.as_deref().unwrap_or(mname.as_str());
            writeln!(out,
                "    if let Some(ref v) = input.{snake} {{ _headers.push((\"{hdr_name}\".into(), v.to_string())); }}",
            ).unwrap();
        }

        if output_type == "()" {
            writeln!(out, "    client.rest_json_request_void(\"{endpoint}\", \"{method}\", &uri, &_query, &_headers, &input).await").unwrap();
        } else {
            writeln!(out, "    client.rest_json_request(\"{endpoint}\", \"{method}\", &uri, &_query, &_headers, &input).await").unwrap();
        }
    } else {
        writeln!(out, "    let uri = \"{uri_template}\";").unwrap();
        if output_type == "()" {
            writeln!(out, "    client.rest_json_request_void(\"{endpoint}\", \"{method}\", uri, &[], &[], &()).await").unwrap();
        } else {
            writeln!(out, "    client.rest_json_request(\"{endpoint}\", \"{method}\", uri, &[], &[], &()).await").unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_rest_xml_op(
    out:    &mut String,
    ctx:    &EmitCtx<'_>,
    name:   &str,
    op:     &crate::model::Operation,
) {
    use crate::model::ShapeRef;

    let rt           = ctx.runtime_crate;
    let fn_name      = to_snake(name);
    let endpoint     = &ctx.model.metadata.endpoint_prefix;

    let http         = op.http.as_ref();
    let method       = http.map(|h| h.method.as_str()).unwrap_or("GET");
    let uri_template = http.map(|h| h.request_uri.as_str()).unwrap_or("/");

    // Split static query params from URI template (e.g. "/{Bucket}?list-type=2")
    let (uri_path, static_qs) = match uri_template.split_once('?') {
        Some((p, q)) => (p, Some(q)),
        None => (uri_template, None),
    };

    let input_type  = op.input.as_ref().map(|r| to_pascal(&r.shape));
    let output_type = op.output.as_ref()
        .map(|r| to_pascal(&r.shape))
        .unwrap_or_else(|| "()".to_string());

    let input_param = input_type.as_ref()
        .map(|t| format!(", input: {t}"))
        .unwrap_or_default();

    writeln!(out, "pub async fn {fn_name}(").unwrap();
    writeln!(out, "    client: &Client{input_param},").unwrap();
    writeln!(out, ") -> Result<{output_type}, AwsError> {{").unwrap();

    if input_type.is_some() {
        let input_shape_name = op.input.as_ref().map(|r| r.shape.as_str()).unwrap_or("");
        let members: Vec<(String, ShapeRef)> = ctx.model.shapes
            .get(input_shape_name)
            .map(|s| s.members.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
            .unwrap_or_default();

        // URI template expansion
        let uri_members: Vec<_> = members.iter()
            .filter(|(_, r)| r.location.as_deref() == Some("uri"))
            .collect();

        let mut fmt_str = uri_path.to_string();
        let mut fmt_args = String::new();
        for (mname, _mref) in &uri_members {
            // Handle {Key+} greedy path params
            let placeholder = format!("{{{mname}}}");
            let placeholder_greedy = format!("{{{mname}+}}");
            let snake = to_snake(mname);
            if fmt_str.contains(&placeholder_greedy) {
                // Greedy: don't percent-encode slashes
                fmt_str = fmt_str.replace(&placeholder_greedy, "{}");
                fmt_args.push_str(&format!("    &input.{snake},\n"));
            } else if fmt_str.contains(&placeholder) {
                fmt_str = fmt_str.replace(&placeholder, "{}");
                fmt_args.push_str(&format!(
                    "    &{rt}::aws::client::percent_encode(&input.{snake}),\n",
                ));
            }
        }

        if uri_members.is_empty() {
            writeln!(out, "    let uri = \"{uri_path}\".to_string();").unwrap();
        } else {
            writeln!(out, "    let uri = format!(\"{fmt_str}\",").unwrap();
            writeln!(out, "{fmt_args}    );").unwrap();
        }

        // Querystring members
        let qs_members: Vec<_> = members.iter()
            .filter(|(_, r)| r.location.as_deref() == Some("querystring"))
            .collect();

        writeln!(out, "    let mut _query: Vec<(String, String)> = vec![];").unwrap();
        // Static query params from URI template
        if let Some(sq) = static_qs {
            for part in sq.split('&') {
                if let Some((k, v)) = part.split_once('=') {
                    writeln!(out, "    _query.push((\"{k}\".into(), \"{v}\".into()));").unwrap();
                }
            }
        }
        for (mname, mref) in &qs_members {
            let snake = to_snake(mname);
            let wire  = mref.wire_name(mname);
            writeln!(out,
                "    if let Some(ref v) = input.{snake} {{ _query.push((\"{wire}\".into(), v.to_string())); }}",
            ).unwrap();
        }

        // Header members (only scalars — lists/structs need custom serialization)
        let hdr_members: Vec<_> = members.iter()
            .filter(|(_, r)| matches!(r.location.as_deref(), Some("header") | Some("headers")))
            .filter(|(_, r)| {
                ctx.model.shapes.get(&r.shape)
                    .map(|s| matches!(s.shape_type.as_str(), "string" | "integer" | "long" | "boolean" | "float" | "double" | "timestamp"))
                    .unwrap_or(true)
            })
            .collect();

        writeln!(out, "    let mut _headers: Vec<(String, String)> = vec![];").unwrap();
        for (mname, mref) in &hdr_members {
            let snake = to_snake(mname);
            let hdr_name = mref.location_name.as_deref().unwrap_or(mname.as_str());
            writeln!(out,
                "    if let Some(ref v) = input.{snake} {{ _headers.push((\"{hdr_name}\".into(), v.to_string())); }}",
            ).unwrap();
        }

        if output_type == "()" {
            writeln!(out, "    client.rest_xml_request_void(\"{endpoint}\", \"{method}\", &uri, &_query, &_headers).await").unwrap();
        } else {
            writeln!(out, "    client.rest_xml_request(\"{endpoint}\", \"{method}\", &uri, &_query, &_headers).await").unwrap();
        }
    } else {
        writeln!(out, "    let uri = \"{uri_path}\";").unwrap();
        if let Some(sq) = static_qs {
            writeln!(out, "    let _query: Vec<(String, String)> = vec![").unwrap();
            for part in sq.split('&') {
                if let Some((k, v)) = part.split_once('=') {
                    writeln!(out, "        (\"{k}\".into(), \"{v}\".into()),").unwrap();
                }
            }
            writeln!(out, "    ];").unwrap();
            if output_type == "()" {
                writeln!(out, "    client.rest_xml_request_void(\"{endpoint}\", \"{method}\", uri, &_query, &[]).await").unwrap();
            } else {
                writeln!(out, "    client.rest_xml_request(\"{endpoint}\", \"{method}\", uri, &_query, &[]).await").unwrap();
            }
        } else if output_type == "()" {
            writeln!(out, "    client.rest_xml_request_void(\"{endpoint}\", \"{method}\", uri, &[], &[]).await").unwrap();
        } else {
            writeln!(out, "    client.rest_xml_request(\"{endpoint}\", \"{method}\", uri, &[], &[]).await").unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_map_type(
    out:       &mut String,
    ctx:       &EmitCtx<'_>,
    name:      &str,
    shape:     &crate::model::Shape,
    in_input:  bool,
    in_output: bool,
) {
    // Maps in query protocol: we emit a newtype wrapper around HashMap.
    // The QueryEncode impl serializes as flat key=value pairs using an
    // "entry.N.key" / "entry.N.value" pattern (used by some EC2 / SQS operations).
    // For JSON protocol, we just use HashMap directly (handled inline in rust_type_by_name).
    if !is_query_protocol(&ctx.model.metadata.protocol) { return; }
    let rt = ctx.runtime_crate;

    let rust_name = to_pascal(name);
    let k_type = shape.key.as_ref()
        .map(|r| rust_type_by_name(&r.shape, ctx.model, false))
        .unwrap_or_else(|| "String".to_string());
    let v_type = shape.value.as_ref()
        .map(|r| rust_type_by_name(&r.shape, ctx.model, false))
        .unwrap_or_else(|| "String".to_string());

    // Non-query protocols: emit a type alias. Field types reference to_pascal(shape_name)
    // which maps to this alias; serde handles HashMap<K,V> deserialization natively.
    if !is_query_protocol(&ctx.model.metadata.protocol) {
        writeln!(out, "pub type {rust_name} = std::collections::HashMap<{k_type}, {v_type}>;").unwrap();
        writeln!(out).unwrap();
        return;
    }

    let key_wire   = shape.key.as_ref().and_then(|r| r.location_name.as_deref()).unwrap_or("key");
    let value_wire = shape.value.as_ref().and_then(|r| r.location_name.as_deref()).unwrap_or("value");

    let mut derives = vec!["Debug", "Clone", "Default"];
    if in_output { derives.push("serde::Deserialize"); }
    writeln!(out, "#[derive({})]", derives.join(", ")).unwrap();
    writeln!(out, "pub struct {rust_name}(pub std::collections::HashMap<{k_type}, {v_type}>);").unwrap();
    writeln!(out).unwrap();

    if in_input {
        writeln!(out, "impl {rt}::aws::query_proto::QueryEncode for {rust_name} {{").unwrap();
        writeln!(out, "    fn encode(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
        writeln!(out, "        for (i, (k, v)) in self.0.iter().enumerate() {{").unwrap();
        writeln!(out, "            let n = i + 1;").unwrap();
        writeln!(out, "            out.push((format!(\"{{prefix}}.{{n}}.{key_wire}\"), k.to_string()));").unwrap();
        writeln!(out, "            out.push((format!(\"{{prefix}}.{{n}}.{value_wire}\"), v.to_string()));").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}


// ─────────────────────────────────────────────────────────────────────────────
// Type helpers
// ─────────────────────────────────────────────────────────────────────────────

/// The Rust field type for a member reference.
/// - `for_output`: lists become the wrapper struct, which is needed for XML deserialization.
///   For input, lists are also wrapper structs (consistent representation).
fn rust_field_type(ctx: &EmitCtx<'_>, member_ref: &crate::model::ShapeRef, for_output: bool) -> String {
    rust_type_by_name(&member_ref.shape, ctx.model, for_output)
}


pub fn rust_type_by_name(shape_name: &str, model: &ServiceModel, _for_output: bool) -> String {
    let Some(shape) = model.shapes.get(shape_name) else {
        return to_pascal(shape_name);
    };

    match shape.shape_type.as_str() {
        "string" => {
            if shape.enum_values.is_some() {
                to_pascal(shape_name)
            } else {
                "String".to_string()
            }
        }
        "integer"   => "i32".to_string(),
        "long"      => "i64".to_string(),
        "float"     => "f32".to_string(),
        "double"    => "f64".to_string(),
        "boolean"   => "bool".to_string(),
        "timestamp" => {
            // JSON protocols send timestamps as epoch floats; XML uses ISO 8601 strings.
            if matches!(model.metadata.protocol.as_str(), "json" | "rest-json") {
                "f64".to_string()
            } else {
                "String".to_string()
            }
        }
        "blob"      => "Vec<u8>".to_string(),
        "list"      => to_pascal(shape_name), // list shapes become wrapper structs
        "map" => {
            if is_query_protocol(&model.metadata.protocol) {
                // Query protocol: wrapper struct is emitted by emit_map_type
                to_pascal(shape_name)
            } else {
                // Non-query protocols: inline HashMap
                let k = shape.key.as_ref()
                    .map(|r| rust_type_by_name(&r.shape, model, false))
                    .unwrap_or_else(|| "String".to_string());
                let v = shape.value.as_ref()
                    .map(|r| rust_type_by_name(&r.shape, model, false))
                    .unwrap_or_else(|| "String".to_string());
                format!("std::collections::HashMap<{k}, {v}>")
            }
        }
        "structure" => to_pascal(shape_name),
        _ => "serde_json::Value".to_string(),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Name mangling utilities
// ─────────────────────────────────────────────────────────────────────────────

/// PascalCase → snake_case
pub fn to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    // Escape Rust keywords
    match out.as_str() {
        "type" | "self" | "move" | "in" | "match" | "loop" | "use" | "return"
        | "for" | "if" | "else" | "let" | "mut" | "ref" | "static" | "fn" => {
            out.insert_str(0, "r#");
        }
        _ => {}
    }
    out
}

/// snake_case or PascalCase → PascalCase
pub fn to_pascal(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// PascalCase → camelCase
fn to_camel(s: &str) -> String {
    let pascal = to_pascal(s);
    let mut chars = pascal.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().collect::<String>() + chars.as_str(),
    }
}

fn sanitize_enum_variant(s: &str) -> String {
    // Replace any non-alphanumeric char with underscore, then PascalCase.
    let cleaned: String = s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    let pascal = to_pascal(&cleaned);
    // Ensure it starts with a letter
    if pascal.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        format!("V{pascal}")
    } else {
        pascal
    }
}

fn strip_html(s: &str) -> String {
    // Very basic HTML tag stripping for doc comments
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    for ch in s.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _   => if !in_tag { out.push(ch); }
        }
    }
    out
}
