use std::collections::HashSet;
use std::fmt::Write as FmtWrite;

use crate::model::{ServiceModel, Shape};
use crate::resolve::ReachableShapes;

// ─────────────────────────────────────────────────────────────────────────────
// Protocol helpers
// ─────────────────────────────────────────────────────────────────────────────

/// EC2 uses protocol "ec2" in the spec, but it's wire-compatible with "query".
fn is_query_protocol(proto: &str) -> bool {
    matches!(proto, "query" | "ec2")
}

// ─────────────────────────────────────────────────────────────────────────────
// Public entry point
// ─────────────────────────────────────────────────────────────────────────────

pub struct EmitCtx<'a> {
    pub model:           &'a ServiceModel,
    pub reachable:       &'a ReachableShapes,
    pub topo_order:      &'a [String],
    pub operations:      &'a [&'a str],
    pub service_name:    &'a str,
    /// Crate path for the aws-api runtime. Defaults to `"aws_api"`.
    /// Set to `"crate"` if the generated code lives inside the aws-api crate itself.
    pub runtime_crate:   &'a str,
}

pub fn emit(ctx: &EmitCtx<'_>) -> String {
    let mut out = String::with_capacity(64 * 1024);
    let proto = ctx.model.metadata.protocol.as_str();

    writeln!(out, "// Auto-generated by aws-codegen — DO NOT EDIT").unwrap();
    writeln!(out, "// service={} protocol={} version={}",
        ctx.service_name,
        proto,
        ctx.model.metadata.api_version,
    ).unwrap();
    // NOTE: the including module should add #[allow(dead_code, non_snake_case, ...)]
    writeln!(out).unwrap();
    let rt = ctx.runtime_crate;
    writeln!(out, "use {rt}::aws::{{Client, AwsError}};").unwrap();
    writeln!(out).unwrap();

    // Emit all shape types in dependency order
    for shape_name in ctx.topo_order {
        let Some(shape) = ctx.model.shapes.get(shape_name.as_str()) else { continue };

        // Skip primitives (string/integer/etc with no enum values) — they inline
        if shape.is_primitive() { continue; }

        let in_input  = ctx.reachable.input.contains(shape_name);
        let in_output = ctx.reachable.output.contains(shape_name);

        match shape.shape_type.as_str() {
            "structure" => emit_structure(&mut out, ctx, shape_name, shape, in_input, in_output),
            "list"      => emit_list_wrapper(&mut out, ctx, shape_name, shape, in_input, in_output),
            "map"       => emit_map_type(&mut out, ctx, shape_name, shape, in_input, in_output),
            "string" if shape.enum_values.is_some() => emit_string_enum(&mut out, ctx, shape_name, shape),
            _ => {}
        }
    }

    // Emit operation async functions
    for &op_name in ctx.operations {
        let Some(op) = ctx.model.operations.get(op_name) else { continue };
        match proto {
            "query"     => emit_query_op(&mut out, ctx, op_name, op),
            "json"      => emit_json_op(&mut out, ctx, op_name, op),
            "rest-json" => emit_rest_json_op(&mut out, ctx, op_name, op),
            "rest-xml"  => emit_rest_xml_op(&mut out, ctx, op_name, op),
            _           => emit_query_op(&mut out, ctx, op_name, op), // fallback
        }
    }

    out
}

// ─────────────────────────────────────────────────────────────────────────────
// Shape emitters
// ─────────────────────────────────────────────────────────────────────────────

fn emit_structure(
    out:       &mut String,
    ctx:       &EmitCtx<'_>,
    name:      &str,
    shape:     &Shape,
    in_input:  bool,
    in_output: bool,
) {
    let rust_name = to_pascal(name);
    let req_set: HashSet<&str> = shape.required.iter().map(String::as_str).collect();

    // Doc comment
    if let Some(doc) = &shape.documentation {
        let first_line = doc.lines().next().unwrap_or("").trim();
        if !first_line.is_empty() {
            writeln!(out, "/// {}", strip_html(first_line)).unwrap();
        }
    }

    // Derives: always Debug; Deserialize when in output context; Serialize for JSON input
    let proto = ctx.model.metadata.protocol.as_str();
    let is_rest_json = proto == "rest-json";
    let is_rest_xml  = proto == "rest-xml";
    let is_rest      = is_rest_json || is_rest_xml;

    let mut derives = vec!["Debug", "Clone", "Default"];
    if in_output {
        derives.push("serde::Deserialize");
    }
    if in_input && (proto == "json" || is_rest_json) {
        derives.push("serde::Serialize");
    }
    writeln!(out, "#[derive({})]", derives.join(", ")).unwrap();

    // Serde rename attributes for wire format compatibility.
    // JSON protocols (SSM, DynamoDB, rest-json) use PascalCase member names.
    // EC2/query uses camelCase in XML. rest-xml (S3) uses PascalCase in XML.
    let has_serde = in_output || (in_input && (proto == "json" || is_rest_json));
    if has_serde {
        match proto {
            "json" | "rest-json" => {
                writeln!(out, "#[serde(rename_all = \"PascalCase\", default)]").unwrap();
            }
            "rest-xml" => {
                writeln!(out, "#[serde(default)]").unwrap();
            }
            _ => {
                // query / ec2: camelCase for output deserialization
                if in_output {
                    writeln!(out, "#[serde(rename_all = \"camelCase\", default)]").unwrap();
                }
            }
        }
    }

    writeln!(out, "pub struct {} {{", rust_name).unwrap();

    for (member_name, member_ref) in &shape.members {
        let rust_field = to_snake(member_name);
        let rust_type  = rust_field_type(ctx, member_ref, in_output);
        let required   = req_set.contains(member_name.as_str());

        // REST protocols: members with a location annotation do NOT go in the JSON body.
        // Only relevant when Serialize is derived (json/rest-json input structs).
        let has_location = member_ref.location.as_deref()
            .map(|loc| matches!(loc, "uri" | "querystring" | "header" | "headers"))
            .unwrap_or(false);
        let has_serde_derive = in_output || (in_input && (proto == "json" || is_rest_json));
        if has_serde_derive && is_rest && has_location {
            writeln!(out, "    #[serde(skip)]").unwrap();
        }

        // Wire name override
        let wire = member_ref.wire_name(member_name);
        if in_output {
            if is_rest_xml {
                // rest-xml: PascalCase XML elements — always need rename from snake_case
                if wire != member_name {
                    // locationName override
                    writeln!(out, "    #[serde(rename = \"{wire}\")]").unwrap();
                } else if to_snake(member_name) != *member_name {
                    // Standard PascalCase → snake_case needs explicit rename back
                    writeln!(out, "    #[serde(rename = \"{member_name}\")]").unwrap();
                }
            } else {
                // camelCase protocols: only rename when wire name differs from camelCase convention
                if wire != &to_camel(member_name) && wire != member_name {
                    writeln!(out, "    #[serde(rename = \"{wire}\")]").unwrap();
                }
            }
        }

        if required {
            writeln!(out, "    pub {rust_field}: {rust_type},").unwrap();
        } else {
            writeln!(out, "    pub {rust_field}: Option<{rust_type}>,").unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // QueryEncode impl for input structs in query-protocol services
    if in_input && is_query_protocol(&ctx.model.metadata.protocol) {
        emit_query_encode_impl(out, ctx, name, shape, &req_set);
    }
}

fn emit_query_encode_impl(
    out:     &mut String,
    ctx:     &EmitCtx<'_>,
    name:    &str,
    shape:   &Shape,
    req_set: &HashSet<&str>,
) {
    let rt = ctx.runtime_crate;
    let rust_name = to_pascal(name);
    writeln!(out, "impl {rt}::aws::query_proto::QueryEncode for {} {{", rust_name).unwrap();
    writeln!(out, "    fn encode(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
    writeln!(out, "        #[allow(unused_imports)]").unwrap();
    writeln!(out, "        use {rt}::aws::query_proto::{{QueryEncode as _, ToAwsStr as _}};").unwrap();
    writeln!(out, "        let p: String = if prefix.is_empty() {{ String::new() }} else {{ format!(\"{{}}.\", prefix) }};").unwrap();

    for (member_name, member_ref) in &shape.members {
        let rust_field = to_snake(member_name);
        let wire_name  = member_ref.wire_name(member_name);
        let required   = req_set.contains(member_name.as_str());
        let member_shape = ctx.model.shapes.get(&member_ref.shape);

        let is_list = member_shape.map(|s| s.shape_type == "list").unwrap_or(false);
        let is_struct = member_shape.map(|s| s.shape_type == "structure").unwrap_or(false);
        let is_map = member_shape.map(|s| s.shape_type == "map").unwrap_or(false);

        if required {
            write!(out, "        ").unwrap();
        } else {
            writeln!(out, "        if let Some(val) = &self.{rust_field} {{").unwrap();
            write!(out, "            ").unwrap();
        }

        if is_list {
            let item_wire = member_shape
                .and_then(|s| s.member.as_ref())
                .and_then(|m| m.location_name.as_deref())
                .unwrap_or(wire_name);
            if required {
                writeln!(out,
                    "self.{rust_field}.encode(&format!(\"{{p}}{wire_name}\"), out);",
                ).unwrap();
            } else {
                writeln!(out,
                    "val.encode_items(&format!(\"{{p}}{item_wire}\"), out);",
                ).unwrap();
            }
        } else if is_struct || is_map {
            if required {
                writeln!(out,
                    "self.{rust_field}.encode(&format!(\"{{p}}{wire_name}\"), out);",
                ).unwrap();
            } else {
                writeln!(out,
                    "val.encode(&format!(\"{{p}}{wire_name}\"), out);",
                ).unwrap();
            }
        } else {
            // Primitive: push directly
            if required {
                writeln!(out,
                    "out.push((format!(\"{{p}}{wire_name}\"), self.{rust_field}.to_aws_str()));",
                ).unwrap();
            } else {
                writeln!(out,
                    "out.push((format!(\"{{p}}{wire_name}\"), val.to_aws_str()));",
                ).unwrap();
            }
        }

        if !required {
            writeln!(out, "        }}").unwrap();
        }
    }

    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_list_wrapper(
    out:       &mut String,
    ctx:       &EmitCtx<'_>,
    name:      &str,
    shape:     &Shape,
    in_input:  bool,
    in_output: bool,
) {
    let rt = ctx.runtime_crate;
    let rust_name = to_pascal(name);
    let item_ref  = match &shape.member {
        Some(m) => m,
        None    => return,
    };
    let item_rust = rust_type_by_name(&item_ref.shape, ctx.model, in_output);
    // The XML element name for list items (from member.locationName, defaulting to "member")
    let item_xml  = item_ref.location_name.as_deref().unwrap_or("member");

    let mut derives = vec!["Debug", "Clone", "Default"];
    if in_output { derives.push("serde::Deserialize"); }
    let is_json = matches!(ctx.model.metadata.protocol.as_str(), "json" | "rest-json");
    if in_input && is_json { derives.push("serde::Serialize"); }

    writeln!(out, "#[derive({})]", derives.join(", ")).unwrap();
    if is_json {
        // JSON protocols: serialize/deserialize as a plain array
        writeln!(out, "#[serde(transparent)]").unwrap();
    } else if in_output {
        writeln!(out, "#[serde(default)]").unwrap();
    }
    writeln!(out, "pub struct {rust_name} {{").unwrap();
    if !is_json && in_output {
        writeln!(out, "    #[serde(rename = \"{item_xml}\", default)]").unwrap();
    }
    writeln!(out, "    pub item: Vec<{item_rust}>,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Convenience: From<Vec<T>>
    writeln!(out, "impl From<Vec<{item_rust}>> for {rust_name} {{").unwrap();
    writeln!(out, "    fn from(v: Vec<{item_rust}>) -> Self {{ Self {{ item: v }} }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // QueryEncode for lists used in query-protocol inputs
    if in_input && is_query_protocol(&ctx.model.metadata.protocol) {
        writeln!(out, "impl {rt}::aws::query_proto::QueryEncode for {rust_name} {{").unwrap();
        writeln!(out, "    fn encode(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
        writeln!(out, "        self.encode_items(prefix, out);").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out, "impl {rust_name} {{").unwrap();
        writeln!(out, "    pub fn encode_items(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
        writeln!(out, "        use {rt}::aws::query_proto::QueryEncode as _;").unwrap();
        writeln!(out, "        for (i, item) in self.item.iter().enumerate() {{").unwrap();
        writeln!(out, "            item.encode(&format!(\"{{}}.{{}}\", prefix, i + 1), out);").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}

fn emit_string_enum(out: &mut String, ctx: &EmitCtx<'_>, name: &str, shape: &Shape) {
    let rt = ctx.runtime_crate;
    let rust_name  = to_pascal(name);
    let enum_vals  = shape.enum_values.as_ref().unwrap();

    writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq, serde::Deserialize, serde::Serialize)]").unwrap();
    writeln!(out, "pub enum {rust_name} {{").unwrap();
    for v in enum_vals {
        let variant = sanitize_enum_variant(v);
        if variant != *v {
            writeln!(out, "    #[serde(rename = \"{v}\")]").unwrap();
        }
        writeln!(out, "    {variant},").unwrap();
    }
    // Always include an Unknown variant to handle future values gracefully
    writeln!(out, "    #[serde(other)] Unknown,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "impl {rt}::aws::query_proto::ToAwsStr for {rust_name} {{").unwrap();
    writeln!(out, "    fn to_aws_str(&self) -> String {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for v in enum_vals {
        let variant = sanitize_enum_variant(v);
        writeln!(out, "            Self::{variant} => \"{v}\".to_string(),").unwrap();
    }
    writeln!(out, "            Self::Unknown => \"unknown\".to_string(),").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    // Display impl (delegates to ToAwsStr, enables .to_string() for querystring use)
    writeln!(out, "impl std::fmt::Display for {rust_name} {{").unwrap();
    writeln!(out, "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{").unwrap();
    writeln!(out, "        use {rt}::aws::query_proto::ToAwsStr as _;").unwrap();
    writeln!(out, "        f.write_str(&self.to_aws_str())").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    // Default impl (defaults to Unknown)
    writeln!(out, "impl Default for {rust_name} {{").unwrap();
    writeln!(out, "    fn default() -> Self {{ Self::Unknown }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    // QueryEncode for enum values used in query-protocol list items
    writeln!(out, "impl {rt}::aws::query_proto::QueryEncode for {rust_name} {{").unwrap();
    writeln!(out, "    fn encode(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
    writeln!(out, "        use {rt}::aws::query_proto::ToAwsStr as _;").unwrap();
    writeln!(out, "        out.push((prefix.to_string(), self.to_aws_str()));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

// ─────────────────────────────────────────────────────────────────────────────
// Operation emitters
// ─────────────────────────────────────────────────────────────────────────────

fn emit_query_op(
    out:    &mut String,
    ctx:    &EmitCtx<'_>,
    name:   &str,
    op:     &crate::model::Operation,
) {
    let rt = ctx.runtime_crate;
    let fn_name    = to_snake(name);
    let endpoint   = &ctx.model.metadata.endpoint_prefix;
    let version    = &ctx.model.metadata.api_version;

    let input_type  = op.input.as_ref().map(|r| to_pascal(&r.shape));
    let output_type = op.output.as_ref()
        .map(|r| to_pascal(&r.shape))
        .unwrap_or_else(|| "()".to_string());

    // Determine if we need to unwrap a resultWrapper intermediate element.
    //
    // EC2  → resultWrapper = "DescribeInstancesResponse" (ends with "Response")
    //        quick-xml reads root element as the struct directly → no envelope needed.
    // IAM  → resultWrapper = "GetUserResult" (ends with "Result")
    //        Response body has an extra <GetUserResult> child wrapping the output.
    let wrapper_element: Option<&str> = op.result_wrapper.as_deref().and_then(|rw| {
        if output_type != "()" && !rw.ends_with("Response") {
            Some(rw)
        } else {
            None
        }
    });

    // Emit a private envelope struct so quick-xml can unwrap the intermediate element.
    if let Some(wrapper) = wrapper_element {
        let env_name = format!("{name}Envelope__");
        writeln!(out, "#[derive(serde::Deserialize)]").unwrap();
        writeln!(out, "struct {env_name} {{").unwrap();
        writeln!(out, "    #[serde(rename = \"{wrapper}\")]").unwrap();
        writeln!(out, "    result: {output_type},").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    let input_param = input_type.as_ref()
        .map(|t| format!(", input: {t}"))
        .unwrap_or_default();

    writeln!(out, "pub async fn {fn_name}(").unwrap();
    writeln!(out, "    client: &Client{input_param},").unwrap();
    writeln!(out, ") -> Result<{output_type}, AwsError> {{").unwrap();

    if input_type.is_some() {
        writeln!(out, "    use {rt}::aws::query_proto::QueryEncode as _;").unwrap();
        writeln!(out, "    let mut params: Vec<(String, String)> = vec![];").unwrap();
        writeln!(out, "    input.encode(\"\", &mut params);").unwrap();
    } else {
        writeln!(out, "    let params: Vec<(String, String)> = vec![];").unwrap();
    }

    if output_type == "()" {
        writeln!(out, "    client.query_request_void(\"{endpoint}\", \"{version}\", \"{name}\", params).await").unwrap();
    } else if wrapper_element.is_some() {
        let env_name = format!("{name}Envelope__");
        writeln!(out, "    let envelope: {env_name} = client.query_request(\"{endpoint}\", \"{version}\", \"{name}\", params).await?;").unwrap();
        writeln!(out, "    Ok(envelope.result)").unwrap();
    } else {
        writeln!(out, "    client.query_request(\"{endpoint}\", \"{version}\", \"{name}\", params).await").unwrap();
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_json_op(
    out:    &mut String,
    ctx:    &EmitCtx<'_>,
    name:   &str,
    op:     &crate::model::Operation,
) {
    let fn_name      = to_snake(name);
    let endpoint     = &ctx.model.metadata.endpoint_prefix;
    let target_pfx   = ctx.model.metadata.target_prefix.as_deref().unwrap_or("");
    let target       = format!("{target_pfx}.{name}");

    let input_type  = op.input.as_ref().map(|r| to_pascal(&r.shape));
    let output_type = op.output.as_ref()
        .map(|r| to_pascal(&r.shape))
        .unwrap_or_else(|| "()".to_string());

    let input_param = input_type.as_ref()
        .map(|t| format!(", input: {t}"))
        .unwrap_or_default();

    writeln!(out, "pub async fn {fn_name}(").unwrap();
    writeln!(out, "    client: &Client{input_param},").unwrap();
    writeln!(out, ") -> Result<{output_type}, AwsError> {{").unwrap();

    if input_type.is_some() {
        writeln!(out, "    client.json_request(\"{endpoint}\", \"{target}\", &input).await").unwrap();
    } else {
        writeln!(out, "    client.json_request(\"{endpoint}\", \"{target}\", &serde_json::json!({{}})).await").unwrap();
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_rest_json_op(
    out:    &mut String,
    ctx:    &EmitCtx<'_>,
    name:   &str,
    op:     &crate::model::Operation,
) {
    use crate::model::ShapeRef;

    let rt           = ctx.runtime_crate;
    let fn_name      = to_snake(name);
    let endpoint     = &ctx.model.metadata.endpoint_prefix;

    let http         = op.http.as_ref();
    let method       = http.map(|h| h.method.as_str()).unwrap_or("POST");
    let uri_template = http.map(|h| h.request_uri.as_str()).unwrap_or("/");

    let input_type  = op.input.as_ref().map(|r| to_pascal(&r.shape));
    let output_type = op.output.as_ref()
        .map(|r| to_pascal(&r.shape))
        .unwrap_or_else(|| "()".to_string());

    let input_param = input_type.as_ref()
        .map(|t| format!(", input: {t}"))
        .unwrap_or_default();

    writeln!(out, "pub async fn {fn_name}(").unwrap();
    writeln!(out, "    client: &Client{input_param},").unwrap();
    writeln!(out, ") -> Result<{output_type}, AwsError> {{").unwrap();

    if let Some(_) = input_type {
        // Collect members by location from the input shape
        let input_shape_name = op.input.as_ref().map(|r| r.shape.as_str()).unwrap_or("");
        let members: Vec<(String, ShapeRef)> = ctx.model.shapes
            .get(input_shape_name)
            .map(|s| s.members.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
            .unwrap_or_default();

        // Build URI: replace {TemplateName} segments
        // Template segments use PascalCase in the spec (e.g., {FunctionName})
        // URI template → collect uri-location members
        // URI template → collect uri-location members
        let uri_members: Vec<_> = members.iter()
            .filter(|(_, r)| r.location.as_deref() == Some("uri"))
            .collect();

        // Rewrite the template format! — replace {X} with {x} for Rust format! compat
        let mut fmt_str = uri_template.to_string();
        let mut fmt_args = String::new();
        for (mname, _mref) in &uri_members {
            let placeholder = format!("{{{mname}}}");
            let snake = to_snake(mname);
            if fmt_str.contains(&placeholder) {
                fmt_str = fmt_str.replace(&placeholder, "{}");
                fmt_args.push_str(&format!(
                    "    &{rt}::aws::client::percent_encode(&input.{snake}),\n",
                ));
            }
        }

        if uri_members.is_empty() {
            writeln!(out, "    let uri = \"{uri_template}\";").unwrap();
        } else {
            writeln!(out, "    let uri = format!(\"{fmt_str}\",").unwrap();
            writeln!(out, "{fmt_args}    );").unwrap();
        }

        // Collect querystring members
        let qs_members: Vec<_> = members.iter()
            .filter(|(_, r)| r.location.as_deref() == Some("querystring"))
            .collect();

        writeln!(out, "    let mut _query: Vec<(String, String)> = vec![];").unwrap();
        for (mname, _mref) in &qs_members {
            let snake = to_snake(mname);
            let wire  = _mref.wire_name(mname);
            writeln!(out,
                "    if let Some(ref v) = input.{snake} {{ _query.push((\"{wire}\".into(), v.to_string())); }}",
            ).unwrap();
        }

        // Collect header members
        let hdr_members: Vec<_> = members.iter()
            .filter(|(_, r)| matches!(r.location.as_deref(), Some("header") | Some("headers")))
            .collect();

        writeln!(out, "    let mut _headers: Vec<(String, String)> = vec![];").unwrap();
        for (mname, mref) in &hdr_members {
            let snake = to_snake(mname);
            let hdr_name = mref.location_name.as_deref().unwrap_or(mname.as_str());
            writeln!(out,
                "    if let Some(ref v) = input.{snake} {{ _headers.push((\"{hdr_name}\".into(), v.to_string())); }}",
            ).unwrap();
        }

        if output_type == "()" {
            writeln!(out, "    client.rest_json_request_void(\"{endpoint}\", \"{method}\", &uri, &_query, &_headers, &input).await").unwrap();
        } else {
            writeln!(out, "    client.rest_json_request(\"{endpoint}\", \"{method}\", &uri, &_query, &_headers, &input).await").unwrap();
        }
    } else {
        writeln!(out, "    let uri = \"{uri_template}\";").unwrap();
        writeln!(out, "    let empty: serde_json::Value = serde_json::json!({{}});").unwrap();
        if output_type == "()" {
            writeln!(out, "    client.rest_json_request_void(\"{endpoint}\", \"{method}\", uri, &[], &[], &empty).await").unwrap();
        } else {
            writeln!(out, "    client.rest_json_request(\"{endpoint}\", \"{method}\", uri, &[], &[], &empty).await").unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_rest_xml_op(
    out:    &mut String,
    ctx:    &EmitCtx<'_>,
    name:   &str,
    op:     &crate::model::Operation,
) {
    use crate::model::ShapeRef;

    let rt           = ctx.runtime_crate;
    let fn_name      = to_snake(name);
    let endpoint     = &ctx.model.metadata.endpoint_prefix;

    let http         = op.http.as_ref();
    let method       = http.map(|h| h.method.as_str()).unwrap_or("GET");
    let uri_template = http.map(|h| h.request_uri.as_str()).unwrap_or("/");

    // Split static query params from URI template (e.g. "/{Bucket}?list-type=2")
    let (uri_path, static_qs) = match uri_template.split_once('?') {
        Some((p, q)) => (p, Some(q)),
        None => (uri_template, None),
    };

    let input_type  = op.input.as_ref().map(|r| to_pascal(&r.shape));
    let output_type = op.output.as_ref()
        .map(|r| to_pascal(&r.shape))
        .unwrap_or_else(|| "()".to_string());

    let input_param = input_type.as_ref()
        .map(|t| format!(", input: {t}"))
        .unwrap_or_default();

    writeln!(out, "pub async fn {fn_name}(").unwrap();
    writeln!(out, "    client: &Client{input_param},").unwrap();
    writeln!(out, ") -> Result<{output_type}, AwsError> {{").unwrap();

    if input_type.is_some() {
        let input_shape_name = op.input.as_ref().map(|r| r.shape.as_str()).unwrap_or("");
        let members: Vec<(String, ShapeRef)> = ctx.model.shapes
            .get(input_shape_name)
            .map(|s| s.members.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
            .unwrap_or_default();

        // URI template expansion
        let uri_members: Vec<_> = members.iter()
            .filter(|(_, r)| r.location.as_deref() == Some("uri"))
            .collect();

        let mut fmt_str = uri_path.to_string();
        let mut fmt_args = String::new();
        for (mname, _mref) in &uri_members {
            // Handle {Key+} greedy path params
            let placeholder = format!("{{{mname}}}");
            let placeholder_greedy = format!("{{{mname}+}}");
            let snake = to_snake(mname);
            if fmt_str.contains(&placeholder_greedy) {
                // Greedy: don't percent-encode slashes
                fmt_str = fmt_str.replace(&placeholder_greedy, "{}");
                fmt_args.push_str(&format!("    &input.{snake},\n"));
            } else if fmt_str.contains(&placeholder) {
                fmt_str = fmt_str.replace(&placeholder, "{}");
                fmt_args.push_str(&format!(
                    "    &{rt}::aws::client::percent_encode(&input.{snake}),\n",
                ));
            }
        }

        if uri_members.is_empty() {
            writeln!(out, "    let uri = \"{uri_path}\".to_string();").unwrap();
        } else {
            writeln!(out, "    let uri = format!(\"{fmt_str}\",").unwrap();
            writeln!(out, "{fmt_args}    );").unwrap();
        }

        // Querystring members
        let qs_members: Vec<_> = members.iter()
            .filter(|(_, r)| r.location.as_deref() == Some("querystring"))
            .collect();

        writeln!(out, "    let mut _query: Vec<(String, String)> = vec![];").unwrap();
        // Static query params from URI template
        if let Some(sq) = static_qs {
            for part in sq.split('&') {
                if let Some((k, v)) = part.split_once('=') {
                    writeln!(out, "    _query.push((\"{k}\".into(), \"{v}\".into()));").unwrap();
                }
            }
        }
        for (mname, mref) in &qs_members {
            let snake = to_snake(mname);
            let wire  = mref.wire_name(mname);
            writeln!(out,
                "    if let Some(ref v) = input.{snake} {{ _query.push((\"{wire}\".into(), v.to_string())); }}",
            ).unwrap();
        }

        // Header members (only scalars — lists/structs need custom serialization)
        let hdr_members: Vec<_> = members.iter()
            .filter(|(_, r)| matches!(r.location.as_deref(), Some("header") | Some("headers")))
            .filter(|(_, r)| {
                ctx.model.shapes.get(&r.shape)
                    .map(|s| matches!(s.shape_type.as_str(), "string" | "integer" | "long" | "boolean" | "float" | "double" | "timestamp"))
                    .unwrap_or(true)
            })
            .collect();

        writeln!(out, "    let mut _headers: Vec<(String, String)> = vec![];").unwrap();
        for (mname, mref) in &hdr_members {
            let snake = to_snake(mname);
            let hdr_name = mref.location_name.as_deref().unwrap_or(mname.as_str());
            writeln!(out,
                "    if let Some(ref v) = input.{snake} {{ _headers.push((\"{hdr_name}\".into(), v.to_string())); }}",
            ).unwrap();
        }

        if output_type == "()" {
            writeln!(out, "    client.rest_xml_request_void(\"{endpoint}\", \"{method}\", &uri, &_query, &_headers).await").unwrap();
        } else {
            writeln!(out, "    client.rest_xml_request(\"{endpoint}\", \"{method}\", &uri, &_query, &_headers).await").unwrap();
        }
    } else {
        writeln!(out, "    let uri = \"{uri_path}\";").unwrap();
        if let Some(sq) = static_qs {
            writeln!(out, "    let _query: Vec<(String, String)> = vec![").unwrap();
            for part in sq.split('&') {
                if let Some((k, v)) = part.split_once('=') {
                    writeln!(out, "        (\"{k}\".into(), \"{v}\".into()),").unwrap();
                }
            }
            writeln!(out, "    ];").unwrap();
            if output_type == "()" {
                writeln!(out, "    client.rest_xml_request_void(\"{endpoint}\", \"{method}\", uri, &_query, &[]).await").unwrap();
            } else {
                writeln!(out, "    client.rest_xml_request(\"{endpoint}\", \"{method}\", uri, &_query, &[]).await").unwrap();
            }
        } else {
            if output_type == "()" {
                writeln!(out, "    client.rest_xml_request_void(\"{endpoint}\", \"{method}\", uri, &[], &[]).await").unwrap();
            } else {
                writeln!(out, "    client.rest_xml_request(\"{endpoint}\", \"{method}\", uri, &[], &[]).await").unwrap();
            }
        }
    }

    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_map_type(
    out:       &mut String,
    ctx:       &EmitCtx<'_>,
    name:      &str,
    shape:     &crate::model::Shape,
    in_input:  bool,
    in_output: bool,
) {
    // Maps in query protocol: we emit a newtype wrapper around HashMap.
    // The QueryEncode impl serializes as flat key=value pairs using an
    // "entry.N.key" / "entry.N.value" pattern (used by some EC2 / SQS operations).
    // For JSON protocol, we just use HashMap directly (handled inline in rust_type_by_name).
    if !is_query_protocol(&ctx.model.metadata.protocol) { return; }
    let rt = ctx.runtime_crate;

    let rust_name = to_pascal(name);
    let k_type = shape.key.as_ref()
        .map(|r| rust_type_by_name(&r.shape, ctx.model, false))
        .unwrap_or_else(|| "String".to_string());
    let v_type = shape.value.as_ref()
        .map(|r| rust_type_by_name(&r.shape, ctx.model, false))
        .unwrap_or_else(|| "String".to_string());

    // Non-query protocols: emit a type alias. Field types reference to_pascal(shape_name)
    // which maps to this alias; serde handles HashMap<K,V> deserialization natively.
    if !is_query_protocol(&ctx.model.metadata.protocol) {
        writeln!(out, "pub type {rust_name} = std::collections::HashMap<{k_type}, {v_type}>;").unwrap();
        writeln!(out).unwrap();
        return;
    }

    let key_wire   = shape.key.as_ref().and_then(|r| r.location_name.as_deref()).unwrap_or("key");
    let value_wire = shape.value.as_ref().and_then(|r| r.location_name.as_deref()).unwrap_or("value");

    let mut derives = vec!["Debug", "Clone", "Default"];
    if in_output { derives.push("serde::Deserialize"); }
    writeln!(out, "#[derive({})]", derives.join(", ")).unwrap();
    writeln!(out, "pub struct {rust_name}(pub std::collections::HashMap<{k_type}, {v_type}>);").unwrap();
    writeln!(out).unwrap();

    if in_input {
        writeln!(out, "impl {rt}::aws::query_proto::QueryEncode for {rust_name} {{").unwrap();
        writeln!(out, "    fn encode(&self, prefix: &str, out: &mut Vec<(String, String)>) {{").unwrap();
        writeln!(out, "        for (i, (k, v)) in self.0.iter().enumerate() {{").unwrap();
        writeln!(out, "            let n = i + 1;").unwrap();
        writeln!(out, "            out.push((format!(\"{{prefix}}.{{n}}.{key_wire}\"), k.to_string()));").unwrap();
        writeln!(out, "            out.push((format!(\"{{prefix}}.{{n}}.{value_wire}\"), v.to_string()));").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}


// ─────────────────────────────────────────────────────────────────────────────
// Type helpers
// ─────────────────────────────────────────────────────────────────────────────

/// The Rust field type for a member reference.
/// - `for_output`: lists become the wrapper struct, which is needed for XML deserialization.
///   For input, lists are also wrapper structs (consistent representation).
fn rust_field_type(ctx: &EmitCtx<'_>, member_ref: &crate::model::ShapeRef, for_output: bool) -> String {
    rust_type_by_name(&member_ref.shape, ctx.model, for_output)
}


pub fn rust_type_by_name(shape_name: &str, model: &ServiceModel, _for_output: bool) -> String {
    let Some(shape) = model.shapes.get(shape_name) else {
        return to_pascal(shape_name);
    };

    match shape.shape_type.as_str() {
        "string" => {
            if shape.enum_values.is_some() {
                to_pascal(shape_name)
            } else {
                "String".to_string()
            }
        }
        "integer"   => "i32".to_string(),
        "long"      => "i64".to_string(),
        "float"     => "f32".to_string(),
        "double"    => "f64".to_string(),
        "boolean"   => "bool".to_string(),
        "timestamp" => {
            // JSON protocols send timestamps as epoch floats; XML uses ISO 8601 strings.
            if matches!(model.metadata.protocol.as_str(), "json" | "rest-json") {
                "f64".to_string()
            } else {
                "String".to_string()
            }
        }
        "blob"      => "Vec<u8>".to_string(),
        "list"      => to_pascal(shape_name), // list shapes become wrapper structs
        "map" => {
            if is_query_protocol(&model.metadata.protocol) {
                // Query protocol: wrapper struct is emitted by emit_map_type
                to_pascal(shape_name)
            } else {
                // Non-query protocols: inline HashMap
                let k = shape.key.as_ref()
                    .map(|r| rust_type_by_name(&r.shape, model, false))
                    .unwrap_or_else(|| "String".to_string());
                let v = shape.value.as_ref()
                    .map(|r| rust_type_by_name(&r.shape, model, false))
                    .unwrap_or_else(|| "String".to_string());
                format!("std::collections::HashMap<{k}, {v}>")
            }
        }
        "structure" => to_pascal(shape_name),
        _ => "serde_json::Value".to_string(),
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Name mangling utilities
// ─────────────────────────────────────────────────────────────────────────────

/// PascalCase → snake_case
pub fn to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    // Escape Rust keywords
    match out.as_str() {
        "type" | "self" | "move" | "in" | "match" | "loop" | "use" | "return"
        | "for" | "if" | "else" | "let" | "mut" | "ref" | "static" | "fn" => {
            out.insert_str(0, "r#");
        }
        _ => {}
    }
    out
}

/// snake_case or PascalCase → PascalCase
pub fn to_pascal(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// PascalCase → camelCase
fn to_camel(s: &str) -> String {
    let pascal = to_pascal(s);
    let mut chars = pascal.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().collect::<String>() + chars.as_str(),
    }
}

fn sanitize_enum_variant(s: &str) -> String {
    // Replace any non-alphanumeric char with underscore, then PascalCase.
    let cleaned: String = s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    let pascal = to_pascal(&cleaned);
    // Ensure it starts with a letter
    if pascal.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        format!("V{pascal}")
    } else {
        pascal
    }
}

fn strip_html(s: &str) -> String {
    // Very basic HTML tag stripping for doc comments
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    for ch in s.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _   => if !in_tag { out.push(ch); }
        }
    }
    out
}
